---
- name: cleanup
  hosts: all
  gather_facts: false
  become: true
  vars:
    three_tier_packages:
      - httpie
      - python-pip
      - haproxy
      - tomcat
      - postgresql-server

  tasks:

    - name: reverse the enabling of sudo without tty for some ansible commands
      replace:
        path: /etc/sudoers
        regexp: 'Defaults\s*!requiretty'
        replace: '^Defaults requiretty'
        backup: yes

    - name: Remove the repo file
      file:
        state: absent
        path: /etc/yum.repos.d/open_three-tier-app.repo

    - name: Remove base tools and three tier app packages
      yum:
        name: "{{ three_tier_packages }}"
        state: absent

    - name: Remove index.html
      file:
        path: /tmp/index.html
        state: absent
...
