== Overview

Bad Ansible is a deliberately poorly constructed ansible project designed to give students a basic project to cleanup, refactor, and improve. It represents a newcomer's, aka _newbie_, approach to hacking together a functional playbook to deploy a three tier app.

The entry point, `main.yml` contains multiple _good enough_ plays, and some redundant ones.

=== Goal of `main.yml`

Set up an application that:

* Sets up a `frontend1` haproxy server which load balances requests to http://frontend1.<GUID>.example.opentlc.com.
** Requests to `frontend1` come in on port 80
** Load balance requests to servers in the group `apps`, listening on port 8080
* Set up one or more tomcat servers, the group `apps`, to:
** Serve the included HTML content from <INSERT PATH HERE>
* Install postgres on all servers in the group appdbs


=== Tips

* Make sure you have read the *Goals* section above and understand the desired architecture
* There are redundant plays within `main.yml`
* Would
* You should be able to run your solution multiple times, not just once
* You are free to restructure your solution in any way


NOTE: Any plays or tasks not related to the above are therefore redundant and can be removed.

TIP: Don't rename any of the ansible groups: `frontends`, `apps`, `appdbs` - later labs require these!

`3tier-bad/main.yml` is playbook currently consisting of


=== Usage

. Set up the environmental variable GUID to your GUID
[source,bash]
----
export GUID=abcd
----
. Execute your main wrapping palaybook
[source,bash]
----
 ansible-playbook main.yml
----

=== Structure

[source,bash]
----
.
├── README.adoc                       <1>
├── ansible.cfg                       <2>
├── cleanup.yml                       <3>
├── haproxy.cfg.j2                    <4>
├── hosts                             <5>
├── index.html.app1                   <6>
├── index.html.app2                   <6>
├── index.html.j2                     <6>
├── main.yml                          <7>
└── ssh.cfg                           <8>
----

. This README file
. Simple ansible.cfg
. Convenience playbook that removes the 3tier app - use to retest your work
. A badly written jinja2 template for HAProxy - *HINTS*
** This should loop over the apps group
** Perhaps the Tomcat port should be a variable?
. inventory file - referenced from `ansible.cfg`
** Note the use of a lookup in line 2, if you prefer consider:
** Hard coding it `GUID=abcd` or passing it in via `-e GUID=abcd`.


=== Potential strategies

3 directories, 11 files


=== BONUS



